// Studio MCP tool names + input/output types. The tool implementations live in
// `studio/mcp/tools.ts` (transport-agnostic: mounted in-process for the embedded
// panel and over StreamableHTTP for external clients). Frozen contract.

import type { DocRev, EditorContext, PreviewState } from "./types";

export const STUDIO_MCP_SERVER_NAME = "studio";

export const STUDIO_TOOLS = {
  describe: "describe",
  getEditorContext: "get_editor_context",
  listPosts: "list_posts",
  scaffoldPost: "scaffold_post",
  previewStatus: "preview_status",
  openPr: "open_pr",
} as const;

/** Fully-qualified tool name as the agent sees it, e.g. `mcp__studio__apply_edit`. */
export type StudioToolName = `mcp__${typeof STUDIO_MCP_SERVER_NAME}__${(typeof STUDIO_TOOLS)[keyof typeof STUDIO_TOOLS]}`;

/** Wildcard for `allowedTools` auto-approval (acceptEdits does not cover MCP tools). */
export const STUDIO_TOOL_WILDCARD = `mcp__${STUDIO_MCP_SERVER_NAME}__*` as const;

// ---- Tool I/O ----
export interface DescribeResult {
  blog: string;
  conventions: string;
  activePostPath: string | null;
  /**
   * Live app-structure digest (framework + key versions, tsconfig path aliases, a
   * reusable-component inventory, and styling/util entry points), generated by scanning
   * the repo at call time so it cannot drift like hand-written docs. Best-effort and
   * optional: omitted when the scan turns up nothing (or the tool runs outside the repo).
   */
  appStructure?: string;
}

export type GetEditorContextResult = EditorContext | { error: "no-editor-context" };

export type ApplyEditResult =
  | { ok: true; rev: DocRev }
  | { ok: false; error: "stale-rev" | "overlap" | "out-of-range" | "path-not-allowed" | "no-active-document"; currentRev?: DocRev };

export interface PostSummary {
  path: string;
  title: string;
  url: string | null;
}

export interface ScaffoldPostInput {
  title: string;
  slug: string;
  headline: string;
  created_at: string;
}
export type ScaffoldPostResult = { ok: true; path: string; url: string } | { ok: false; error: string };

export type PreviewStatusResult = PreviewState;

export interface OpenPrInput {
  branch: string;
  subject: string;
  body: string;
  scope: "post" | "all";
  confirm: boolean;
}
export type OpenPrResult = { ok: true; prUrl: string } | { ok: false; error: string; violations?: string[] };
