import ConsoleTypist from "@components/console";
import { css } from '@emotion/react';
import {getAllPosts} from '@lib/post';
import {isDefined, notNull} from '@lib/util'
import styles from '@styles/Home.module.css'
import {Post} from '@tina/__generated__/types'

import {NextPage, GetStaticProps} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {useCallback, useMemo, useState} from "react";

type PostWithHeadline = Post & {
    headline: NonNullable<string>
}

interface Headline {
    text: string
    color: string
    href?: string
}

interface Props {
    headlines: Headline[]
}

const defaultHeadline: Headline = {
    text: "Absolutely Nothing.",
    color: "#000000",
}

export const getStaticProps: GetStaticProps<Props> = async () => {
    const query = await getAllPosts()
    const posts: Post[] = query.map(result => result.data)

    const headlines: Headline[] = posts
        .filter((post): post is PostWithHeadline => isDefined(post.headline) && notNull(post.headline))
        .map(post => {
            return {
                text: post.headline,
                color: '#000000',
                href: `/blog/${post.slug}`,
            }
        })
        .filter(notNull) || [defaultHeadline]

    return {
        props: {
            headlines
        }
    }
}

const Home: NextPage<Props> = ({headlines}: Props) => {
    const [index, setIndex] = useState(0)
    const advanceHeadline = useCallback(() => setIndex(i => i + 1), [])

    const headline = useMemo(() => {
        const headline = headlines[index % headlines.length]

        return (
            <a href={headline.href} css={css({fontFamily: 'monospace'})}>
                <ConsoleTypist text={headline.text} onTypingFinished={advanceHeadline} />
            </a>
        )
    }, [headlines, index])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Ryan <br/>
                    Rowe <br/>
                    Codes
                </h1>
                <h3>
                    {headline}
                </h3>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
